### ISSUE TITLE
有提交禅道帮助文档吗?

### ISSUE THREAD

**Issue by yufengTester** [Meituan-Dianping/lyrebird-bugit#5]

**Comment by dodosophia** [comment]
具体指什么呢。。

**Comment by dodosophia** [comment]
> _No description provided._

具体指？？

**Comment by zhaoye** [comment]
示例里面JIRA相关的接口要换成禅道的接口吧。
接口详见 https://www.zentao.net/book/api/bug-create-388.html
@yufengTester
